services:
  gateway-service:
    build:
      context: ./
      dockerfile: Dockerfile.gateway_service     
    container_name: gateway_service
    ports:
      - "8080:8080"               
    environment:
      SERVICE_PORT: :8080
      USER_SERVICE_ADDRESS: user_service:5051
      VAULT_HOST: vault:8200
      KVSTORE_NAME: signing_key
      KVPATH_NAME: keys
      VAULT_TOKEN: ${VAULT_TOKEN}
    networks:
      - kai
    depends_on:
      cassandra3:
        condition: service_healthy
      vault:
        condition: service_started

  user-service:
    build:
      context: ./    
      dockerfile: Dockerfile.user_service     
    container_name: user_service
    ports:
      - "5051:5051"               
    networks:
      - kai
    environment:
      SERVICE_PORT: :5051
      MONGO_DB_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo
      CASSANDRA_CLUSTER: cassandra1,cassandra2,cassandra3
    restart: unless-stopped
    depends_on:
      gateway-service:    
        condition: service_started
      mongo:
        condition: service_healthy
      cassandra3:
        condition: service_healthy  
      vault:
        condition: service_started

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "bash", "-c", "mongosh --username $MONGO_INITDB_ROOT_USERNAME --password $MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase admin --eval 'db.runCommand({ ping: 1 })'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 3s
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb-data:/data/db
      - ./mongodb-scripts/init.js:/docker-entrypoint-initdb.d/init.js
    networks:
      - kai

  cassandra1: 
    image: cassandra:latest 
    container_name: cassandra1  
    hostname: cassandra1 
    networks: 
      - kai 
    ports: 
      - "9042:9042" 
    volumes:
      - cassandra_data1:/var/lib/cassandra
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'DESCRIBE KEYSPACES' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment: &environment  
        CASSANDRA_SEEDS: "cassandra1,cassandra2"
        CASSANDRA_CLUSTER_NAME: TestCluster
        CASSANDRA_DC: DC1
        CASSANDRA_RACK: RACK1
        CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
        CASSANDRA_NUM_TOKENS: 128

  cassandra2: 
    image: cassandra:latest 
    container_name: cassandra2
    hostname: cassandra2
    networks:
      - kai
    ports:
      - "9043:9042"
    volumes:
      - cassandra_data2:/var/lib/cassandra
    restart: unless-stopped
    environment: *environment
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'DESCRIBE KEYSPACES' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      cassandra1:
        condition: service_started

  cassandra3:
    image: cassandra:latest
    container_name: cassandra3
    hostname: cassandra3
    networks:
      - kai
    ports:
      - "9044:9042"
    volumes:
      - cassandra_data3:/var/lib/cassandra
    restart: unless-stopped
    environment: *environment
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'DESCRIBE KEYSPACES' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      cassandra2:
        condition: service_started

  cassandra1-init:
    image: cassandra:latest
    container_name: cassandra1-init
    depends_on:
      - cassandra1
    entrypoint: ["sh", "-c", "until cqlsh cassandra1 -e 'DESCRIBE KEYSPACES'; do sleep 1; done; cqlsh cassandra1 -f /cql-scripts/init.cql"]
    volumes:
      - ./cql-scripts:/cql-scripts
    networks:
      - kai

  # just dev mode for now
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
    volumes:
      - vault_data:/vault/data
      - ./vault/vault.hcl:/vault/vault.hcl
    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/vault.hcl
    networks:
      - kai

# Change the volumes to you local path
volumes:
  mongodb-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/kamisama/Desktop/mongodb
  cassandra_data1:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/kamisama/Desktop/cassandra/cassandra1
  cassandra_data2:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/kamisama/Desktop/cassandra/cassandra2
  cassandra_data3:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/kamisama/Desktop/cassandra/cassandra3
  vault_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/kamisama/Desktop/vault/vault_data

networks:
  kai:
